### PR TITLE
Fail if any checks were failures

### LINKED ISSUE #22: Fail if any check has been failures
Currently if you run `codechecks` it always exited with code 0, even if any check is failed. I'm not sure, but I believe CLI should fail in that case as well.

### PR DESCRIPTION
**Pull request by MichalZalecki**
This one is intended to finally fix #22. I consider this a breaking change (duh!).

### CODE REVIEW

**Comment by krzkaczor** [comment]
Thanks for this! I just had a really quick look at this PR. 

This behavior HAS to be controlled via a command-line flag. Based on my experience, on CI you never want the whole CLI to fail. Often CC can be run as a single step in a bigger job. I get that sometimes it might be useful (especially for running checks locally) to return non-zero exit code but I don't believe that it should be the default behavior.

**Comment by MichalZalecki** [comment]
@krzkaczor I thought about it and I'm not so sure it should be behind a feature flag. When I run my tests and a test fails I want CI to fail (and maybe not deploy if that's part of the pipeline). Why would I like it to work differently in case of codechecks? I think this would be the users' expectation and it's better to be safe than sorry (and fail the CI).

> Often CC can be run as a single step in a bigger job.
Yes, and then you can manage dependencies on different steps in your CI of choice.

I'm happy to make a new flag but I would personally prefer that using it returns 0 when there're failures than return non-0 code on failure. In other words, I believe it should be the default behavior, not an opt-in.

Also, you have a complex CI? You can figure out the flag.
Do you have something simple? You probably skipped on reading docs.

File: packages/client/src/getExecutionContext.ts [hunk 1]
```diff
@@ -25,6 +25,8 @@ export async function getConstExecutionContext(
     throw new Error("Provider should never be in fork mode and not in PR mode!");
   }
 
+  const isWithExitStatus: boolean = !!args.withExitStatus;
```
Comment (krzkaczor) [inline packages/client/src/getExecutionContext.ts]: Does it have to be part of `sharedExecutionContext`?  Idea behind execution context is to provide all important info to plugins. I can't think of a case when this would be valuable info for plugins as this is simply CLI argument.

File: packages/client/src/runner.ts [hunk 2]
```diff
@@ -67,24 +70,42 @@ async function main(
...
+    successCodechecks > 0 ? bold(green(`${successCodechecks} succeeded`)) : false,
+    `${failureCodechecks + successCodechecks} total`,
+  ]
+    .filter(Boolean)
+    .join(", ");
+
+  logger.log(`${bold("Checks:")} ${result}`);
+  logger.log(`${bold("Time:")}   ${ms(deltaTime)}`);
+
+  if (sharedExecutionCtx.isWithExitStatus && failureCodechecks > 0) {
```
Comment (krzkaczor) [inline packages/client/src/runner.ts]: I believe here we could access `isWithExitStatus` directly from args.

**Comment by krzkaczor** [comment]
@MichalZalecki I hear you. As I said, this was how I always imagined it to work, but it's not necessarily the right view 😆

I would put it as another input for 0.2.0 release and have hopefully more people wage into a discussion.

I feel like it's a much larger discussion - should CC be just a suggestion for a reviewers or should it really block CI pipeline.

File: packages/client/src/getExecutionContext.ts (hunk 1 above)
Comment (MichalZalecki) [reply packages/client/src/getExecutionContext.ts]: No, it doesn't have to be. I tried to use the abstraction that was already there without trying to come up with something else living next to it. Honestly, I was waiting for some comment like this one 😉

File: packages/client/src/runner.ts (hunk 2 above)
Comment (MichalZalecki) [reply packages/client/src/runner.ts]: I'm hesitant to use this directly from args. I don't want to use it directly to avoid refactorings when the same information can not only be set via process args but also configured in codechecks.yml or using an environment variable. These are fairly plausible ways to influence the way CC can be run (in the future).

I can come up with the abstraction layer for config instead.

Comment (krzkaczor) [reply packages/client/src/runner.ts]: > I can come up with the abstraction layer for config instead.

yes this seems like a way to go 👍

**Comment by MichalZalecki** [comment]
@krzkaczor It's only a thin abstraction but allows runner-only options can be kept as part of `RunnerConfig` and not mix it with a shared context.

**Comment by krzkaczor** [comment]
Thanks for this! Merging!
